version: '3.6'
services:
  gitlab:
    image: gitlab/gitlab-ce
    restart: always
    hostname: mygitlab
    container_name: mygitlab
    networks:
      - gitlabnet
    environment:
      GITLAB_ROOT_PASSWORD : 'Abcd@0123456789'
      GITLAB_OMNIBUS_CONFIG : |
        external_url 'http://mygitlab:8088'
    ports:
      - '8088:8088'
      - '8443:443'
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab
    # shm_size: '256m'

  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    restart: always
    container_name: gitlab-runner 
    depends_on:
      - gitlab
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock
      - gitlab-runner_dat:/etc/gitlab-runner
    networks:
      - gitlabnet

networks:
  gitlabnet:
    name: gitlabnet
    driver: bridge

volumes:
  gitlab_data:
  gitlab_config:
  gitlab_logs:
  gitlab-runner_data: